rubykube/peatio-trading-ui

app/assets/stylesheets/application.scss, app/assets/stylesheets/layouts/_positions.scss, app/assets/stylesheets/vars/_bootstrap_market.scss, app/views/markets/_ask_entry.html.erb, app/views/markets/_bid_entry.html.erb, config/locales/server.en.yml
- Rename and clarify color variables
- Remove hardcoded colors in CSS files
- Add option to invert columns layout
=> Prepare SASS for easy customisation

app/assets/javascripts/component_ui/candlestick.js.coffee
Fixed Candlestick data disappearing issue #27
=> Fix broken candlestick

app/assets/javascripts/component_ui/candlestick.js.coffee
=> Fix charts building issue (closes #26)

app/assets/stylesheets/application.scss, app/assets/stylesheets/layouts/_basic.scss, app/assets/stylesheets/layouts/_positions.scss
Fixed All texts have invalid colors (too white)
=> Fix text colors (too white, closes #43)

app/assets/stylesheets/application.scss
Fixed Buttons have invalid colors and hover colors
=> Fix button colors and hover colors (closes #42)

app/assets/stylesheets/application.scss
Fixed Invalid color for errors when placing orders
=> Fix color for errors when placing orders (closes #41)

app/views/markets/_my_orders.html.erb
Fixed Trade page have unnecessary Sign in option
=> Remove duplicate «Sign in option» (fixes #22)

app/assets/javascripts/component_ui/candlestick.js.coffee
Fix Candlestick bar is visible in line view #45
=> Improve candlestick bar visibility logic when using «Live view» (closes #45)

app/assets/stylesheets/application.scss
Fixed Text is not visible in the inputs #40
=> Fix text is not visible in the inputs (fixes #40)

app/assets/stylesheets/application.scss
=> Fix currency color at order panel (fixes #53)

app/assets/stylesheets/application.scss
Fix the price hint should be red. #55
=> Make the price hint red (closes #55)

app/assets/stylesheets/application.scss, app/assets/stylesheets/layouts/_positions.scss, app/assets/stylesheets/vars/_market.scss
Increased width for Ask/Bid orders #47
=> Increase width for ask/bid orders panel (closes #47)

app/assets/javascripts/component_ui/candlestick.js.coffee
Highcharts-series is missing #64
=> Add missing highcharts-series (closes #64)

app/assets/stylesheets/layouts/_positions.scss
The color changing bid/ask upon crating new orders or trades #69
=> Fix problem related to dynamic colors of ask & bid orders in list when trading (closes #69)

app/helpers/application_helper.rb, app/views/markets/_settings.html.erb, config/templates/application.yml.erb
Change Relative Path To Absolute URL
=> Change Relative Path To Absolute URL

Gemfile, Gemfile.lock
=> Update Gem Sprockets [1-4]

Gemfile, Gemfile.lock
=> Update Gem Sprockets [1-5]

Gemfile, Gemfile.lock
=> Update Gem Sprockets [1-6]

Gemfile, Gemfile.lock
=> Update Gem Sprockets [1-7]

Gemfile, Gemfile.lock
=> Update Gem Sprockets [1-8]

Gemfile, Gemfile.lock
=> Update Gem Sprockets [master]

config/templates/application.yml.erb
=> Chnage Default Root Urls [1-8]

app/assets/javascripts/component_ui/account_summary.js.coffee
=> Fixed Account Summary Balance

app/assets/javascripts/component_ui/account_summary.js.coffee
Issue:- https://jira.openware.work/browse/PHIBITS-1
=> Fixed Account Balance not updated

app/helpers/application_helper.rb, app/views/markets/_settings.html.erb, config/templates/application.yml.erb
=> Redirect To New UI Url [master]
